sudo: required
language: node_js
node_js:
- 8

cache:
  directories:
  - node_modules

install:
- sudo apt-get install -y graphviz
- dot -V || true
- npm prune
- npm install
- npm list --depth 0 || true

script:
- npm run lint
- npm run buildexample
